#!/bin/bash
# Cleanup Test Data Script
# Deletes all test data generated by the Matrix Testing Suite

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Load environment variables
if [ -f .env ]; then
  source .env
fi

# Default values
SUPABASE_URL="${SUPABASE_URL:-https://xgubaguglsnokjyudgvc.supabase.co}"
ANON_KEY="${SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhndWJhZ3VnbHNub2tqeXVkZ3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwOTU3NzMsImV4cCI6MjA4MjY3MTc3M30._fBqrJhF8UWkbo2b4m_f06FFtr4h0-4wGer2Dbn8BBA}"
SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-}"
SSO_BASE="${SUPABASE_URL}/functions/v1"
TEST_PASSWORD="${TEST_PASSWORD:-TestPass123!}"

# Admin credentials
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@sharpsir.group}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-admin1234}"

echo "========================================="
echo "Matrix Testing Suite - Test Data Cleanup"
echo "========================================="
echo ""
echo "⚠️  WARNING: This will delete ALL test data including:"
echo "  - Test users (all *.test.*@sharpsir.group, cy.*@cyprus-sothebysrealty.com, hu.*@sothebys-realty.hu)"
echo "  - Test tenants (Hungary tenant)"
echo "  - Test groups (CY-*, HU-* groups)"
echo "  - Test permissions"
echo "  - Test members records"
echo "  - Test contacts, meetings, and other application data"
echo ""
read -p "Are you sure you want to continue? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
  echo "Cleanup cancelled."
  exit 0
fi

# Authenticate as admin
authenticate_admin() {
  echo "Authenticating as admin..."
  AUTH_RESPONSE=$(curl -s -X POST "${SUPABASE_URL}/auth/v1/token?grant_type=password" \
    -H "apikey: ${ANON_KEY}" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"${ADMIN_EMAIL}\",\"password\":\"${ADMIN_PASSWORD}\"}")
  
  ADMIN_TOKEN=$(echo "$AUTH_RESPONSE" | jq -r '.access_token // empty' 2>/dev/null || echo "")
  
  if [ -z "$ADMIN_TOKEN" ] || [ "$ADMIN_TOKEN" = "null" ]; then
    echo "❌ Failed to authenticate as admin"
    exit 1
  fi
  
  echo "✅ Admin authenticated"
}

# Delete test users by email pattern
delete_test_users() {
  echo ""
  echo "=== Deleting Test Users ==="
  
  # Get all users
  USERS_RESPONSE=$(curl -s -X GET "${SSO_BASE}/admin-users" \
    -H "Authorization: Bearer ${ADMIN_TOKEN}")
  
  # Test user email patterns
  TEST_PATTERNS=(
    "membertype.*@sharpsir.group"
    "*.test.*@sharpsir.group"
    "cy.*@cyprus-sothebysrealty.com"
    "hu.*@sothebys-realty.hu"
    "test.automation.*@sharpsir.group"
    "broker1.test.*@sharpsir.group"
    "broker2.test.*@sharpsir.group"
    "permission.test.*@sharpsir.group"
    "sso.console.test.*@sharpsir.group"
    "oauth.test.*@sharpsir.group"
    "user.manager.test.*@sharpsir.group"
    "regular.user.test.*@sharpsir.group"
    "actas.test.*@sharpsir.group"
    "delete.test.*@sharpsir.group"
    "perm.test.*@sharpsir.group"
    "tenant-test-*@example.com"
    "tenant-update-*@example.com"
  )
  
  # Extract user emails and IDs
  USER_EMAILS=$(echo "$USERS_RESPONSE" | jq -r '.users[]? | select(.email) | "\(.id)|\(.email)"' 2>/dev/null || echo "")
  
  DELETED_COUNT=0
  while IFS='|' read -r USER_ID USER_EMAIL; do
    if [ -z "$USER_ID" ] || [ -z "$USER_EMAIL" ]; then
      continue
    fi
    
    # Check if email matches any test pattern
    IS_TEST_USER=false
    for pattern in "${TEST_PATTERNS[@]}"; do
      # Convert glob pattern to regex
      REGEX=$(echo "$pattern" | sed 's/\./\\./g' | sed 's/\*/.*/g')
      if echo "$USER_EMAIL" | grep -qE "^${REGEX}$"; then
        IS_TEST_USER=true
        break
      fi
    done
    
    if [ "$IS_TEST_USER" = true ]; then
      echo "  Deleting user: $USER_EMAIL (ID: $USER_ID)"
      DELETE_RESPONSE=$(curl -s -X DELETE "${SSO_BASE}/admin-users/${USER_ID}" \
        -H "Authorization: Bearer ${ADMIN_TOKEN}" 2>&1 || echo "")
      
      if echo "$DELETE_RESPONSE" | grep -qE "(error|Error|failed|Failed)"; then
        echo "    ⚠️  Warning: $DELETE_RESPONSE"
      else
        DELETED_COUNT=$((DELETED_COUNT + 1))
      fi
    fi
  done <<< "$USER_EMAILS"
  
  echo "✅ Deleted $DELETED_COUNT test users"
}

# Delete test groups
delete_test_groups() {
  echo ""
  echo "=== Deleting Test Groups ==="
  
  GROUPS_RESPONSE=$(curl -s -X GET "${SSO_BASE}/admin-groups" \
    -H "Authorization: Bearer ${ADMIN_TOKEN}")
  
  # Test group name patterns
  TEST_GROUP_PATTERNS=(
    "CY-Sales-Team"
    "CY-Operations-Team"
    "HU-Sales-Team"
    "HU-Operations-Team"
  )
  
  GROUP_IDS=$(echo "$GROUPS_RESPONSE" | jq -r '.[]? | select(.group_name) | "\(.id)|\(.group_name)"' 2>/dev/null || echo "")
  
  DELETED_COUNT=0
  while IFS='|' read -r GROUP_ID GROUP_NAME; do
    if [ -z "$GROUP_ID" ] || [ -z "$GROUP_NAME" ]; then
      continue
    fi
    
    # Check if group name matches any test pattern
    IS_TEST_GROUP=false
    for pattern in "${TEST_GROUP_PATTERNS[@]}"; do
      if [ "$GROUP_NAME" = "$pattern" ]; then
        IS_TEST_GROUP=true
        break
      fi
    done
    
    if [ "$IS_TEST_GROUP" = true ]; then
      echo "  Deleting group: $GROUP_NAME (ID: $GROUP_ID)"
      DELETE_RESPONSE=$(curl -s -X DELETE "${SSO_BASE}/admin-groups/${GROUP_ID}" \
        -H "Authorization: Bearer ${ADMIN_TOKEN}" 2>&1 || echo "")
      
      if echo "$DELETE_RESPONSE" | grep -qE "(error|Error|failed|Failed)"; then
        echo "    ⚠️  Warning: $DELETE_RESPONSE"
      else
        DELETED_COUNT=$((DELETED_COUNT + 1))
      fi
    fi
  done <<< "$GROUP_IDS"
  
  echo "✅ Deleted $DELETED_COUNT test groups"
}

# Delete Hungary tenant
delete_test_tenants() {
  echo ""
  echo "=== Deleting Test Tenants ==="
  
  # Get Hungary tenant
  TENANTS_RESPONSE=$(curl -s -X GET "${SUPABASE_URL}/rest/v1/tenants?slug=eq.hungary-sir&select=id,name" \
    -H "apikey: ${SERVICE_ROLE_KEY:-${ANON_KEY}}" \
    -H "Authorization: Bearer ${SERVICE_ROLE_KEY:-${ADMIN_TOKEN}}")
  
  HU_TENANT_ID=$(echo "$TENANTS_RESPONSE" | jq -r 'if type=="array" then .[0].id else .id end // empty' 2>/dev/null || echo "")
  
  if [ -n "$HU_TENANT_ID" ] && [ "$HU_TENANT_ID" != "null" ]; then
    echo "  Deleting Hungary tenant: $HU_TENANT_ID"
    DELETE_RESPONSE=$(curl -s -X DELETE "${SUPABASE_URL}/rest/v1/tenants?id=eq.${HU_TENANT_ID}" \
      -H "apikey: ${SERVICE_ROLE_KEY:-${ANON_KEY}}" \
      -H "Authorization: Bearer ${SERVICE_ROLE_KEY:-${ADMIN_TOKEN}}" \
      -H "Prefer: return=representation" 2>&1 || echo "")
    
    if echo "$DELETE_RESPONSE" | grep -qE "(error|Error|failed|Failed)"; then
      echo "    ⚠️  Warning: $DELETE_RESPONSE"
    else
      echo "✅ Deleted Hungary tenant"
    fi
  else
    echo "ℹ️  Hungary tenant not found (may already be deleted)"
  fi
}

# Delete test members records (DEPRECATED - members table removed)
# User data is now in auth.users.user_metadata, cleaned up when user is deleted
delete_test_members() {
  echo ""
  echo "=== Skipping Members Table Cleanup (table removed) ==="
  echo "✅ Member data is stored in auth.users.user_metadata and will be deleted with users"
}

# Delete test application data (contacts, meetings, etc.)
delete_test_application_data() {
  echo ""
  echo "=== Deleting Test Application Data ==="
  
  # Get test user IDs
  USERS_RESPONSE=$(curl -s -X GET "${SSO_BASE}/admin-users" \
    -H "Authorization: Bearer ${ADMIN_TOKEN}")
  
  TEST_USER_IDS=$(echo "$USERS_RESPONSE" | jq -r '.users[]? | select(.email) | select(.email | test(".*\\.test\\..*@sharpsir\\.group|cy\\..*@cyprus-sothebysrealty\\.com|hu\\..*@sothebys-realty\\.hu")) | .id' 2>/dev/null || echo "")
  
  # Use user IDs directly (members table removed)
  # Delete contacts
  DELETED_CONTACTS=0
  while IFS= read -r TEST_USER_ID; do
    if [ -z "$TEST_USER_ID" ]; then
      continue
    fi
    
    CONTACTS_RESPONSE=$(curl -s -X GET "${SUPABASE_URL}/rest/v1/contacts?owning_user_id=eq.${TEST_USER_ID}&select=id" \
      -H "apikey: ${SERVICE_ROLE_KEY:-${ANON_KEY}}" \
      -H "Authorization: Bearer ${SERVICE_ROLE_KEY:-${ADMIN_TOKEN}}")
    
    CONTACT_IDS=$(echo "$CONTACTS_RESPONSE" | jq -r '.[]?.id // empty' 2>/dev/null || echo "")
    
    while IFS= read -r CONTACT_ID; do
      if [ -n "$CONTACT_ID" ] && [ "$CONTACT_ID" != "null" ]; then
        curl -s -X DELETE "${SUPABASE_URL}/rest/v1/contacts?id=eq.${CONTACT_ID}" \
          -H "apikey: ${SERVICE_ROLE_KEY:-${ANON_KEY}}" \
          -H "Authorization: Bearer ${SERVICE_ROLE_KEY:-${ADMIN_TOKEN}}" > /dev/null 2>&1 || true
        DELETED_CONTACTS=$((DELETED_CONTACTS + 1))
      fi
    done <<< "$CONTACT_IDS"
  done <<< "$TEST_USER_IDS"
  
  # Delete entity_events (meetings)
  DELETED_MEETINGS=0
  while IFS= read -r TEST_USER_ID; do
    if [ -z "$TEST_USER_ID" ]; then
      continue
    fi
    
    MEETINGS_RESPONSE=$(curl -s -X GET "${SUPABASE_URL}/rest/v1/entity_events?owning_user_id=eq.${TEST_USER_ID}&select=id" \
      -H "apikey: ${SERVICE_ROLE_KEY:-${ANON_KEY}}" \
      -H "Authorization: Bearer ${SERVICE_ROLE_KEY:-${ADMIN_TOKEN}}")
    
    MEETING_IDS=$(echo "$MEETINGS_RESPONSE" | jq -r '.[]?.id // empty' 2>/dev/null || echo "")
    
    while IFS= read -r MEETING_ID; do
      if [ -n "$MEETING_ID" ] && [ "$MEETING_ID" != "null" ]; then
        curl -s -X DELETE "${SUPABASE_URL}/rest/v1/entity_events?id=eq.${MEETING_ID}" \
          -H "apikey: ${SERVICE_ROLE_KEY:-${ANON_KEY}}" \
          -H "Authorization: Bearer ${SERVICE_ROLE_KEY:-${ADMIN_TOKEN}}" > /dev/null 2>&1 || true
        DELETED_MEETINGS=$((DELETED_MEETINGS + 1))
      fi
    done <<< "$MEETING_IDS"
  done <<< "$TEST_USER_IDS"
  
  echo "✅ Deleted $DELETED_CONTACTS test contacts and $DELETED_MEETINGS test meetings"
}

# Main execution
authenticate_admin
delete_test_users
delete_test_groups
delete_test_tenants
delete_test_members
delete_test_application_data

echo ""
echo "========================================="
echo "Test Data Cleanup Complete"
echo "========================================="
echo ""
echo "✅ All test data has been deleted."
echo ""
echo "Note: Test permissions are automatically deleted when users are deleted"
echo "      (due to foreign key constraints with CASCADE)."

